### ISSUE TITLE
Removed from Google PlayStore?

### ISSUE THREAD

**Issue by nikolayg** [mrpdaemon/encdroid#103]
The app seems to be removed from the app store. It doesn't appear in the search and the provided link doesn't work.

Can you please re-publish or review what the issues is?

**Comment by mailych** [comment]
I am switching to new phone next week. I would appreciate if you can resolve the issue and publish it in play store.

**Comment by mailych** [comment]
I used  EDS lite and was able to import EncFs containers created with EncDroid into it.
https://play.google.com/store/apps/details?id=com.sovworks.edslite

**Comment by RoboPolaris** [comment]
its disappeared like all the other encrypting tools which make clouds more safety. I think there are people who don't want us to save our data safety in the net because they would like to have a look into it. Its a shame!

By the way: Mark R. Pariente who is listed as the Copyright-Owner of Encdroid works for Google since some years. Maybe thats the reason?

Does anybody knows where to find the source code of "Encdroid Multi Cloud"?

**Comment by mrpdaemon** [comment]
I have simply lost interest in developing or maintaining this app. The Google Play removal was because Google requires developers to actively maintain their apps (upgrade to newer target API versions, incorporate security fixes to libraries used etc.) and automatically removes apps that are deemed abandoned from that perspective. The removal from Play Store had nothing to do with my employment status at Google. The app source code is still available since it will forever be open source and can be built by anyone. If there's anyone who is interested in maintaining the project going forward I'd be happy to help getting them up to speed.

**Comment by hkramski** [comment]
DroidFS (https://github.com/hardcore-sushi/DroidFS) seems alive and supports gocryptfs and CryFS.
