### ISSUE TITLE
merge encdroid and cryptonite

### ISSUE THREAD

**Issue by edgimar** [mrpdaemon/encdroid#91]
encdroid and [cryptonite](https://github.com/neurodroid/cryptonite) provide the same functionality overall, and seem like a lot of duplication of effort.  Perhaps any the features of both could be merged into one of these projects to get a larger user-base and more support.  It seems that encdroid does a nice job with user-interface, while cryptonite is functionally stable.  It might be some work to merge the two, but in the long run it seems like it would be worth it.

**Comment by Francewhoa** [comment]
Good idea edgimar :) +1 for that. I would be happy to contribute testing and documentation.

Merging could potentially add a new useful feature to cryptonite. About storing EncFS volume on external storage. Such as USB key or flashdrive. encdroid is able to do that. cryptonite doesn't seem to have that feature yet. Related ticket at https://github.com/neurodroid/cryptonite/issues/114

**Comment by mrpdaemon** [comment]
Cryptonite maintainer seems to have stopped working on the project. Looking at their code it seems like they went a different route (using upstream encfs C++ code via fuse) whereas encdroid is a userspace implementation of EncFS from scratch in Java. Due to the architectural differences there's no possibility of merging these projects in a meaningful way. I'm very happy to accept any patches from interested cryptonite developers to extend Encdroid's functionality.
